name: Program Code Linter
on:
  push:
      branches: main

jobs:
  ProgramCodeLinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code in Repo
        uses: actions/checkout@v3
        
     - name: Super-Linter
        uses: github/super-linter@v4.9.7
        env:
          VALIDATE_PYTHON: true
          FILTER_REGEX_INCLUDE: ./*.py
          GITHUB_TOKEN: ${{secrets.TOKEN}}
